name: deploy-types

on:
  push:
    branches:
      - master
    paths:
      - 'types/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd types && docker build -t mykoladubr/types .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mykoladubr/types
      #- uses: digitalocean/action-doctl@v2
      #  with:
      #    token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #- run: doctl kubernetes cluster kubeconfig save storage_dev
      #- run: kubectl rollout restart deployment types-depl
