  
name: tests-types

on:
  pull_request:
    paths:
      - 'types/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd types && npm install && npm run test:ci
